num = int(input())
print("A ", end = "")
if (num % 2 == 0 and num % 25 == 0): print("+ ", end = "")
else: print("- ", end = "")
print("B ", end = "")
if (num % 2 != 0 and num % 25 == 0): print("+ ", end = "")
else: print("- ", end = "")
print("C ", end = "")
if (num % 8 == 0): print("+ ", end = "")
else: print("- ", end = "")